### ISSUE TITLE
Pointers needed for slicing trajectory and topology together 

### ISSUE THREAD

**Issue by slochower** [Amber-MD/pytraj#1528] opened 2020-04-15 16:50 UTC
I'm trying to slice my trajectory (by frames) and my topology (by residues). I know there's some trickery here in the bookkeeping and I think I'm getting tripped up. Here's an example of what I want to do:

Let's say I slice my trajectory so that it only contains lipids by choosing an atom that only appears in the lipids and I keep track of the residue indices as I go along:

```
t = traj["@P1"]
residue_indices = []
for residue in t.top.residues:
    residue_indices.append(residue.index)
...
frame_x = [i[0] for i in t.xyz[0]]
...
```

Then I do some analysis and decide that residue `231` in frame 0 has some interesting property and I want go back to full trajectory (for example) and find out what protein residues are near this interesting residue. Or maybe I want to simply calculate the lipid order parameter for that residue. But as soon as I go back to the full trajectory, residue `231` is an amino acid, not a lipid:

```
for atom in traj.top[":231"].atoms:
    print(atom.name)

N
CA
C
O
CB
```

I know I've seen you post about about slicing topology and trajectories and how things get reindexed, but I can't find the relevant documentation.

**Comment by hainm** [comment] 2020-04-15 18:06
hi @slochower, you can try `res.index`, which is the original index (zero based index). 
https://github.com/Amber-MD/pytraj/blob/be334e0e98cd141f542a7a6de42751fd18b55a86/pytraj/core/topology_objects.pyx#L223-L226

PS: I am considering to rename it from `index` to `original_index`.

**Comment by hainm** [comment] 2020-04-15 18:07
Oh, please use `original_resid`

https://github.com/Amber-MD/pytraj/blob/be334e0e98cd141f542a7a6de42751fd18b55a86/pytraj/core/topology_objects.pyx#L216-L221

**Comment by hainm** [comment] 2020-04-15 18:08
> Oh, please use original_resid 

1-based index to be consistent with `cpptraj`. (that I introduced `index` for 0-based).

**Comment by slochower** [comment] 2020-04-20 19:43
Thanks @hainm. Hmm, I think I understand but perhaps I'm not implementing your idea correctly. Here's a super quick example:

```python
p = traj["@P1"]
for residue in p.top.residues:
    print(residue.name)

POP
POP
etc...
```
Then:

```python
for residue in p.top.residues:
    print(residue.original_resid + 1)
2
3
4
etc...
```
Now, I expect that when I go back to the original, un-sliced trajectory, I should be able to use these `resid`s, right?

```python
traj[":2"]
pytraj.Trajectory, 1003 frames: 
Size: 0.000247 (GB)
<Topology: 11 atoms, 1 residues, 1 mols, PBC with box type = ortho>
```

But that atom count isn't correct for POPC. (I don't know how to interrogate the residue names of `traj[":2"]` directly.) It might be worth noting I'm using a `pdb` and `dcd` trajectory here, and I wonder if that could be leading to some parsing problems because the PDB has different chains.

**Comment by hainm** [comment] 2020-04-20 20:23
ah,
`original_resid` is 1-based and Amber residue selection syntax is 1-based too.
So `traj[":2"]` should be `traj[":1"]`. In other words, you can use `res.original_resid` directly

`traj[res.original_resid]`

**Comment by hainm** [comment] 2020-04-20 20:24
```
for residue in p.top.residues:
    print(residue.original_resid + 1) # should be print(residue.original_resid)
```

**Comment by slochower** [comment] 2020-04-20 20:48
Ah, oops, my mistake. But I still don't think I'm getting the right selection.

`traj.top[":1"]` grabs something with 7 atoms, but I expect there to be 134 atoms.

![image](https://user-images.githubusercontent.com/5393995/79798201-80fb7c80-830d-11ea-8885-d15d8dcc85b4.png)

How does `traj.top[":1"]` handle chains? Is it supposed to grab residue 1 in each chain?

**Comment by hainm** [comment] 2020-04-20 21:15
@slochower `pytraj` is `cpptraj` under the hood.
So please see here: https://github.com/Amber-MD/cpptraj/pull/548

What the residue name in your example?
```code
{res.name for res in traj.top[':1'].residues}
```

**Comment by slochower** [comment] 2020-04-20 21:38
I think this is the crux of the issue that I'm encountering: the sliced trajectory is showing a mapping from "1" to POP (a lipid) but the full trajectory maps "1" to PRO.

![image](https://user-images.githubusercontent.com/5393995/79802306-91fbbc00-8314-11ea-8311-2012e2ef7656.png)

**Comment by hainm** [comment] 2020-04-20 22:08
do you mind to share a toy system so I can test it myself? 
Or can you reproduce your issue with the system in here? http://ambermd.org/tutorials/advanced/tutorial16/

**Comment by hainm** [comment] 2020-04-20 23:09
My guess the issue is due to your pdb file. Does residue starts with 1 and are residue number continuous? `traj.top[':1']` means 1st residue.

**Comment by slochower** [comment] 2020-04-20 23:13
I'll try to reproduce it with a toy example or prune down this system, but might take me a couple of days. Thanks for continuing to think about this.

I agree this might be explained by the PDB file. I started taking a look and noticed there were a bunch of different chains in ways that I didn't quite expect (protein, ligands, water). This trajectory was setup with Maestro and run with Desmond, so getting a workable PDB/DCD was not straightforward. (I have not had good luck with `structconvert`, so I used VMD's DTR plugin and PDB/DCD export.)

**Comment by hainm** [comment] 2020-04-20 23:20
Yeah, but please try again with standard Amber files (in my previous post) to see if you can reproduce the issue (I've tried and pytraj seems work fine).

**Comment by slochower** [comment] 2020-04-20 23:40
Do you know of any mechanism to take a CMS/DTR pair and transform them to `prmtop`/`nc` to make using `pytraj` with Desmond-produced trajectories easier?

**Comment by hainm** [comment] 2020-04-21 01:10
Unfortunately I don't know for sure.

May be try to use `parmed`o convert `cms` to pdb file that preserver the atom order in dtr.
Something like this: https://github.com/arose/nglview/blob/e95a816161eb619de33e291e896ad24965b9f69d/nglview/adaptor.py#L565-L580

`cpptraj` recently adds support for `dtr` directly (https://github.com/Amber-MD/cpptraj/pull/796) but I am not sure if this format is widely tested in cpptraj (cc @drroe). 

If above works, you can use the converted pdb with dtr. But I am not sure.

**Comment by slochower** [comment] 2020-04-23 00:48
I took a look at the `nglview` code and I'm not sure I understand clearly what's happening since there's a couple layers of subclassing `Structure` (which is an nlgview `Structure` and not a ParmEd one, I believe). Do you know if this line is trying to parse the contents of the `cms` file as a string? https://github.com/arose/nglview/blob/e95a816161eb619de33e291e896ad24965b9f69d/nglview/adaptor.py#L571

@drroe any tips for using CMS/DTR files with `cpptraj`?

**Comment by hainm** [comment] 2020-04-23 18:14
oh sorry. Do you have schrodinger suite to load the cms file?
That's the only way I can think of

```python
        from schrodinger.application.desmond.cms import Cms
        import parmed as pmd
        c = Cms('your.cms')
        s = pmd.Structure()
        fsys = c.fsys_ct
        for atom in fsys.atom:
            parm_atom = pmd.Atom(name=atom.pdbname.strip(),
                                 atomic_number=atom.atomic_number)
            s.add_atom(parm_atom,
                       atom.pdbres.strip(),
                       atom.resnum,
                       chain=atom.chain)
        s.coordinates = fsys.getXYZ()
        s.write("your.pdb")
```

**Comment by slochower** [comment] 2020-04-24 21:30
Ah, yes. Sorry for not clarifying. Thanks, Hai.

After minor edits, your script works (I had to figure out how to install ParmEd into the $SCHRODINGER `virtualenv` and change `write` to `write_pdb`). When using a recent-ish `cpptraj` from GitHub, I get a disagreement in atom numbers between the PDB and DTR. Do you think this is due to virtual sites? (Also, do you reckon that `renumber=False` needs to be passed when using ParmEd to save the PDB?)

```
> trajin XXX-duplicate_trj/clickme.dtr
  [trajin XXX-duplicate_trj/clickme.dtr]
	Reading 'XXX-duplicate_trj/clickme.dtr' as Desmond DTR
Error: # of atoms in DTR (216125) != # atoms in associated topology (216124)
```

**Comment by hainm** [comment] 2020-04-24 23:19
>  Do you think this is due to virtual sites? 

yeah, I think so.

>  (Also, do you reckon that renumber=False needs to be passed when using ParmEd to save the PDB?)

I don't think so.

**Comment by slochower** [comment] 2020-04-28 18:16
Hm. Instead of using the above script (https://github.com/Amber-MD/pytraj/issues/1528#issuecomment-618563438) to covert to a PDB, I tried using `$SCHRODINGER/utilities/structconvert`. In this case, `cpptraj` can't read the topology from the PDB file:
```
Warning: tmp.pdb: Determining default bond distances from element types.
Error: Atom 20929 was assigned a lower molecule # (5) than previous atom (6).
Error:   This can happen if bond information is incorrect or missing, or if the
Error:   atom numbering in molecules is not sequential. Try one of the
Error:   following:
Error: - If this is a PDB file, try using the 'noconect' keyword.
Error: - If this topology did not have bond info, try increasing the bond
Error:   search cutoff above 0.2 Ang. ('bondsearch <cutoff>').
Error: - Use the 'fixatomorder' command to reorder the topology and any
Error:   associated coordinates.
Error: - Use the 'setMolecules' command in parmed to reorder only the
Error:   topology.
Error: Could not determine molecule information for tmp.pdb.
Error: SetSolventInfo: No molecule information.
Error: Could not determine solvent information for tmp.pdb.
```

So I think this is my summary:
- I can use another tool (e.g., VMD) to take Desmond trajectories to a PDB/DCD combo, but because of nonstandard (or unexpected/unusual) naming and chains in the PDB file, using `pytraj` for analysis is not straightforward. 
- I can use the Schrodinger API to write out a PDB file, but the number of atoms doesn't match with the DTR trajectory, which eliminates `cpptraj` for analysis.
- I can use the Schrodinger tool `structconvert` to directly write a PDB from the input CMS file, but `cpptraj` has difficulty parsing this PDB file.

**Comment by hainm** [comment] 2020-05-26 05:50
I close this issue since the original issue is resolved. The later issue is tracked (closed) in here: https://github.com/Amber-MD/cpptraj/issues/815

Feel free to open new issue. Cheers.

**Comment by drroe** [comment] 2020-05-26 14:51
Hi,

> Ah, yes. Sorry for not clarifying. Thanks, Hai.
> 
> After minor edits, your script works (I had to figure out how to install ParmEd into the $SCHRODINGER `virtualenv` and change `write` to `write_pdb`). When using a recent-ish `cpptraj` from GitHub, I get a disagreement in atom numbers between the PDB and DTR. Do you think this is due to virtual sites? (Also, do you reckon that `renumber=False` needs to be passed when using ParmEd to save the PDB?)
> 
> ```
> > trajin XXX-duplicate_trj/clickme.dtr
>   [trajin XXX-duplicate_trj/clickme.dtr]
> 	Reading 'XXX-duplicate_trj/clickme.dtr' as Desmond DTR
> Error: # of atoms in DTR (216125) != # atoms in associated topology (216124)
> ```

Sorry for the late reply. Someone else had this issue recently, and found that Schrodinger tools couldn't make a PDB that would work with the DTR file (I think it did in fact have to do with cirtual sites), but VMD could. So maybe try to make the PDB with VMD and use that.

Adding support for CMS is possible but my to-do list is already a bit out of control...

**Comment by drroe** [comment] 2020-05-26 14:52
> I think this is the crux of the issue that I'm encountering: the sliced trajectory is showing a mapping from "1" to POP (a lipid) but the full trajectory maps "1" to PRO.
> 
> ![image](https://user-images.githubusercontent.com/5393995/79802306-91fbbc00-8314-11ea-8311-2012e2ef7656.png)

If you want to go by the "original" residue number you should use `:;` instead of `:`.

**Comment by slochower** [comment] 2020-05-26 22:56
> Sorry for the late reply. Someone else had this issue recently, and found that Schrodinger tools couldn't make a PDB that would work with the DTR file (I think it did in fact have to do with cirtual sites), but VMD could. So maybe try to make the PDB with VMD and use that.

👋That was me too. I should have circled back around to this issue and linked that one here. This hyperlink should do the trick:  https://github.com/Amber-MD/cpptraj/issues/815 

> Adding support for CMS is possible but my to-do list is already a bit out of control...

Got it. CMS seems like it'll be a pain to work with.

**Comment by slochower** [comment] 2020-05-26 22:56
> If you want to go by the "original" residue number you should use `:;` instead of `:`.

Interesting! I didn't know this trick. Thanks.

**Comment by hainm** [comment] 2020-06-02 03:19
We can close this issue now. Thanks all for the discussion.

**Closed by hainm** 2020-06-02 03:19 UTC
Labels: API
