### ISSUE TITLE
rdf question

### ISSUE THREAD

**Issue by jdmadura** [Amber-MD/pytraj#1165] opened 2016-03-10 16:31 UTC
When I use the rdf() command to calculate the radial distribution function between a water oxygen and a small molecule atom the shape of the g(r) looks fine; however, the actual values appear to be low.  The water-water rdfs look fine.  The Ipython notebook is attached.  The trajectory file is 33 MB in size.
[pytraj_md.ipynb.zip](https://github.com/Amber-MD/pytraj/files/167562/pytraj_md.ipynb.zip)

**Comment by hainm** [comment] 2016-03-10 18:51
@drroe and @swails buzz you if you either of you can reply to @jdmadura. thanks.

I re-upload the notebook github can render it. (@jdmadura: let me know when you want me to remove it).
https://github.com/hainm/notes/blob/master/pytraj_users/pytraj_md.ipynb

This is doc for `pytraj.rdf`: http://amber-md.github.io/pytraj/latest/_api/pytraj.all_actions.html#pytraj.all_actions.calc_rdf

**Comment by drroe** [comment] 2016-03-10 18:59
Probably a normalization thing. What does pytraj do under the hood for 'density' (or does it use 'volume')?

**Comment by hainm** [comment] 2016-03-10 19:05
@Dan: pytraj use default `density=0.033456`

>  (or does it use 'volume')?

No, pytraj does not use 'volume' keyword.

**Comment by hainm** [comment] 2016-03-10 19:10
@jdmadura can you try adding: `density=None` in your rdf input?

```python
pt.rdf(traj, solvent_mask=':TIP3@OH2', solute_mask=':DOP@N23', 
         density=None, bin_spacing=0.05, maximum=8.)
```

**Comment by drroe** [comment] 2016-03-10 19:57
I just did a test calculation with cpptraj for a simple system (trpzip2 beta hairpin in water) in both orthogonal and truncated octahedal cells. Here is the cpptraj input:
```
rdf out rdf.agr 0.05 8 :WAT@O :WAT@O O_O
rdf out rdf.agr 0.05 8 :WAT@O :WAT@H= O_H nointramol
```
Results for both are below; looks good to me.
![rdf formatted](https://cloud.githubusercontent.com/assets/10144183/13682494/3e29ccfc-e6bf-11e5-9b75-6f8b5b22458f.jpg)
![rdf formatted](https://cloud.githubusercontent.com/assets/10144183/13682511/503bc24c-e6bf-11e5-9c21-2de3cfad21a8.jpg)
@jdmadura out of curiosity if you repeat the calculation with just cpptraj do you still obtain the same results? This way we can decide if it's an underlying cpptraj issue or not.

**Comment by hainm** [comment] 2016-03-10 20:01
@drroe 

from @jdmadura's 1st comment 
> The water-water rdfs look fine. 

The issue is in
> a water oxygen and a small molecule atom

**Comment by hainm** [comment] 2016-03-10 20:08
@Dan: also, you can try your trajectory with pytraj command

```python
traj = pt.load('tz2.ortho.nc', 'tz2.ortho.parm7')
x = pt.rdf(traj, solvent_mask=':WAT@O', 
                  solute_mask=':WAT@H=', 
                  intramol=False, bin_spacing=0.05, maximum=8)
from matplotlib import pyplot as plt
plt.plot(x[0], x[1])
plt.show()
```

should be equal to `rdf out rdf.agr 0.05 8 :WAT@O :WAT@H= O_H nointramol`

**Comment by hainm** [comment] 2016-03-10 20:26
ack, to reproduce your plot, need to switch solute_mask and solvent mask

```python
traj = pt.load('tz2.ortho.nc', 'tz2.ortho.parm7')
x = pt.rdf(traj, solute_mask=':WAT@O', 
                  solvent_mask=':WAT@H=', 
                  intramol=False, bin_spacing=0.05, maximum=8)
from matplotlib import pyplot as plt
plt.plot(x[0], x[1])
plt.show()
```

**Comment by hainm** [comment] 2016-03-10 20:49
@drroe I just make a PR here #

Per my confusion: I read the test case for cpptraj in Test_Radial folder 
```bash
parm ../tz2.truncoct.parm7
trajin ../tz2.truncoct.nc 1 10

radial Radial.agr    0.5 10.0 :5@CD  :WAT@O
radial cRadial.agr   0.5 10.0 :5     :WAT@O center1
```

So I misunderstood that `:5@CD` is solute mask and `:WAT@O` is solvent mask.

But according to your help message: `:WAT@O` should be solute.

**Comment by drroe** [comment] 2016-03-10 20:55
> Per my confusion: I read the test case for cpptraj in Test_Radial folder

Test case does not equal use case. Ideally it would always be so, but for whatever reason years and years ago I wrote the test in this way. The manual, help text, and ultimately the code (in that order) are the arbiters of correct usage.

**Comment by hainm** [comment] 2016-03-10 21:04
ok got it. I chose test cases in cpptraj so that I just need to copy and paste

see this

```python
In [7]: cm = """
parm ../tz2.truncoct.parm7
trajin ../tz2.truncoct.nc 1 10

radial Radial.agr    0.5 10.0 :5@CD  :WAT@O
radial cRadial.agr   0.5 10.0 :5     :WAT@O center1
"""

In [8]: state = pt.load_cpptraj_state(cm)

In [9]: state.run()
Out[9]: 
CpptrajState, include:
<datasetlist: 3 datasets>

In [10]: state.data[1:].to_dict()         
Out[10]: 
OrderedDict([(':5@CD => :WAT@O',
              array([ 0.        ,  0.        ,  0.        , ...,  0.00039883,
                      0.00041042,  0.00038547])),
             (':5 => :WAT@O',
              array([ 0.        ,  0.        ,  0.        , ...,  0.00034897,
                      0.00046098,  0.00042027]))])
```

This is really convenient to compare pytraj and cpptraj's output. :))

**Comment by jdmadura** [comment] 2016-03-11 01:16
I just tried reversing the solvent mask and solute mask in my notebook and the rdf plots came out fine.  Thank-you for the help.

**Comment by hainm** [comment] 2016-03-11 01:28
Cool. With the ipdaed code, you dont need to reverse.

Closing issue now, feel free to open new one or reopen. Cheers.

**Closed by hainm** 2016-03-11 01:28 UTC
