### ISSUE TITLE
Has anyone tried a Python 3.11 conda package build yet?

### ISSUE THREAD

**Issue by swails** [Amber-MD/pytraj#1632] opened 2023-05-24 17:28 UTC
Attempts to do this for AmberTools 23 are failing.

build log here: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=700933&view=logs&j=9a864fd9-6c8f-52ca-79ce-2aa6dca1a1de&t=10fc5aa2-324e-5982-4c88-6b31fcab16b3)

PR here: https://github.com/conda-forge/ambertools-feedstock/pull/113

**Comment by hainm** [comment] 2023-05-24 17:56
I have not tried with python 3.11 yet.

`pytraj/trajectory/frame.cpp:45333:1: error: too many initializers for 'PyTypeObject' {aka '_typeobject'}`

`frame.cpp` file is generated by cython. wondering if we can have better luck with latest cython version?

**Comment by DrDomenicoMarson** [comment] 2023-06-08 13:55
Hi,
I can confirm that I have the same issue building amber23 in an Anaconda environment with python 3.11.3 + cython 0.29.35.

Is there some workaround that can be done to successfully build pytraj? I'd hate to have to disable its installation!

**Comment by DrDomenicoMarson** [comment] 2023-06-08 14:37
Unfortunatelly I don't know how to do that (I'm not compiling from pytraj git repo, but from AmberTools23).

To briefly describe what I've done:
- I created a conda environment with python3.11
- added cython, numpy, mpi4py, and other dependencies

- ran cmake (python is successfully found)
- when running make install the above errors stop the installation, while if I exclude pytraj from the required packages, everything is compiled successfully!

Doesn't the cmake procedure cythonize the files with the available cython?

**Comment by hainm** [comment] 2023-06-09 03:14
Please:
- force re-cythonizing by updating scripts/base_setup.py to change
is_release from True to False

And continue to rebuild ambertools

Let me know if this works. I am on vacation so I don’t have a chance to
try.

Hai

**Comment by DrDomenicoMarson** [comment] 2023-06-09 06:32
Hi! I'm sorry to bother you on vacation!

I tried as you suggested, but the same error

`pytraj/core/c_dict.cpp:460:62: error: invalid use of incomplete type 'PyFrameObject' {aka 'struct _frame'}`

unfortunatelly arise...


I checked the `make` output, and indeed the `is_release` seems to be recognized. I just paste here the relevant part of the `make` output, because another warning is also raised:

```bash
[ 79%] Building pytraj native library
sys.argv ['setup.py', 'build', '-b', '/opt/amber22_src/build/AmberTools/src/pytraj/CMakeFiles/python-build']
Original compiler envs
CXX = /opt/anaconda3/envs/p11/bin/g++
CC = /opt/anaconda3/envs/p11/bin/gcc
COMPILER = 
use_pip = False, cpptraj_home = 
compile_c_extension = True
2.0.6.dev0
use_prebuilt_cythonized_files =  False
[ 82%] Built target sander_base_obj_omp
pytraj is inside AMBERHOME
using environment: CC=/opt/anaconda3/envs/p11/bin/gcc, CXX=/opt/anaconda3/envs/p11/bin/g++
using CC=/opt/anaconda3/envs/p11/bin/gcc, CXX=/opt/anaconda3/envs/p11/bin/g++
Final compiler envs
CXX = /opt/anaconda3/envs/p11/bin/g++
CC = /opt/anaconda3/envs/p11/bin/gcc
COMPILER = 
install = True
set rpath to /opt/amber22_src/build/AmberTools/src/cpptraj/src
/opt/anaconda3/envs/p11/lib/python3.11/site-packages/setuptools/dist.py:755: SetuptoolsDeprecationWarning: Invalid dash-separated options
!!

        ********************************************************************************
        Usage of dash-separated 'description-file' will not be supported in future
        versions. Please use the underscore name 'description_file' instead.

        By 2023-Sep-26, you need to update your project and remove deprecated calls
        or your builds will no longer be supported.

        See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
        ********************************************************************************

!!
  opt = self.warn_dash_deprecation(opt, section)
running build
running build_py
copying pytraj/version.py -> /opt/amber22_src/build/AmberTools/src/pytraj/CMakeFiles/python-build/lib.linux-x86_64-cpython-311/pytraj
running build_ext
skipping 'pytraj/analysis/c_analysis/c_analysis.cpp' Cython extension (up-to-date)
skipping 'pytraj/analysis/c_action/actionlist.cpp' Cython extension (up-to-date)
skipping 'pytraj/analysis/c_action/c_action.cpp' Cython extension (up-to-date)
skipping 'pytraj/math/cpp_math.cpp' Cython extension (up-to-date)
skipping 'pytraj/topology/topology.cpp' Cython extension (up-to-date)
skipping 'pytraj/core/topology_objects.cpp' Cython extension (up-to-date)
skipping 'pytraj/core/coordinfo.cpp' Cython extension (up-to-date)
skipping 'pytraj/core/parameter_types.cpp' Cython extension (up-to-date)
skipping 'pytraj/core/c_dict.cpp' Cython extension (up-to-date)
skipping 'pytraj/core/c_options.cpp' Cython extension (up-to-date)
skipping 'pytraj/core/box.cpp' Cython extension (up-to-date)
skipping 'pytraj/core/c_core.cpp' Cython extension (up-to-date)
skipping 'pytraj/utils/cyutils.cpp' Cython extension (up-to-date)
skipping 'pytraj/datafiles/datafiles.cpp' Cython extension (up-to-date)
skipping 'pytraj/datasets/c_datasetlist.cpp' Cython extension (up-to-date)
skipping 'pytraj/datasets/c_datasets.cpp' Cython extension (up-to-date)
skipping 'pytraj/datasets/cast_dataset.cpp' Cython extension (up-to-date)
skipping 'pytraj/trajectory/frame.cpp' Cython extension (up-to-date)
skipping 'pytraj/trajectory/c_traj/c_trajout.cpp' Cython extension (up-to-date)
skipping 'pytraj/trajectory/c_traj/c_trajectory.cpp' Cython extension (up-to-date)
building 'pytraj.core.c_dict' extension
```

**Comment by hainm** [comment] 2023-06-09 08:04
Um, I will give this a try when I gave access to my laptop. Cheers.

**Comment by hainm** [comment] 2023-06-10 03:07
On Fri, Jun 9, 2023 at 3:04 PM Hai Nguyen ***@***.***> wrote:

> Um, I will give this a try when I gave access to my laptop. Cheers.


I don’t have a chance to try amber yet but the standalone pytraj compiled
 fine with python 3.11 and cython 0.29.x

So I suggest to also delete all existing cythonized files .cpp in pytraj
and then build again.

And sorry for all the troubles.
Hai

>

**Comment by DrDomenicoMarson** [comment] 2023-06-12 09:36
Just a quick update, deleting all the *.cpp files in the src/pytraj/pytraj directory worked fine with python3.11!

(I also had scripts/base_setup.py with is_release setted to False)

**Comment by hainm** [comment] 2023-06-12 11:54
Great. Thanks.

**Comment by hainm** [comment] 2023-06-20 21:28
I think we can close this case since the question is answered. https://github.com/Amber-MD/pytraj/issues/1632#issuecomment-1586964715 

Further discussions are happening in https://github.com/conda-forge/ambertools-feedstock

**Closed by hainm** 2023-06-20 21:28 UTC
