### ISSUE TITLE
Segmentation fault on pytra.dssp_allresidues

### ISSUE THREAD

**Issue by hectormartinezdev** [Amber-MD/pytraj#1443] opened 2018-01-29 12:46 UTC
Issue type
-------------
* Bug

Useful info
-------------

```
>>> pytraj.show_versions()
2.7.12 (default, Dec  4 2017, 14:50:18) 
[GCC 5.4.0 20160609]

('pytraj version = ', '2.0.0')
('cpptraj version = ', u'V17.00')
('cpptraj internal version = ', u'V4.3.3')
('cpptraj compiled flag = ', u' -DHASBZ2 -DHASGZ -DBINTRAJ')
```

Actual behaviour
---------------------
Hey! I'm using pytraj to calculate the DSSP of a pocket.

```
import pytraj as pt

traj = pt.load("bad_pocket.pdb")
print(pt.dssp_allresidues(traj, simplified=True))
```

When I use this the code crashes with a `Segmentation fault (core dumped)`

Any insights?

**Note**: I've uploaded the pocket in PDB format with txt extension.

Thank you!

[bad_pocket.txt](https://github.com/Amber-MD/pytraj/files/1673411/bad_pocket.txt)

**Comment by hainm** [comment] 2018-01-30 01:49
hi,

your pdb does not have H atom to determine h-bond (and I don't think that is a legit pdb format). Can you add H and try again?

**Comment by hmarlo** [comment] 2018-01-30 08:45
I've added H's with pymol, but fail anyway.

As you say, I think that isn't a legit PDB format. Here there is only one chain, but actually there are two chains. I get NA's using mdtraj with the same pocket, so... my bad.

I will compute the DSSP of the structure and then map these with the pocket residues.

Sorry for bothering! Thank you :)

**Comment by drroe** [comment] 2018-01-30 17:33
@hainm I think that even though this isn't a "good" PDB, pytraj should still not segfault. CPPTRAJ will process this but just complains that not all backbone atoms were found for all residues. It's a low priority fix however.

**Comment by hainm** [comment] 2018-01-30 18:12
@drroe: I've tried cpptraj

parm x.pdb
trajin x.pdb
dssp

will show the segmentation fault.

Hai

**Comment by drroe** [comment] 2018-01-30 19:12
@hainm try with the latest version. It runs. I suspect that pytraj with latest libcpptraj.so will run as well. I had assumed that all of this was being done with all components up to date.

**Comment by hainm** [comment] 2018-01-30 19:49
thanks. I will try tonight.

**Comment by hainm** [comment] 2018-01-31 01:21
uhm, cpptraj is fine and pytraj is not.

**Comment by hmarlo** [comment] 2018-01-31 07:38
I'm compiling right now AmberTools17 from source. I was using it, but I compiled it months ago. I will edit when I test the new compiled version.

**Comment by hainm** [comment] 2018-01-31 20:30
yeah, as we mentioned above, pytraj is not working properly.

**Comment by hainm** [comment] 2020-06-02 04:13
@drroe I've opened a new issue in cpptraj here: https://github.com/Amber-MD/cpptraj/issues/819

**Comment by drroe** [comment] 2020-06-02 20:00
Will be addressed by https://github.com/Amber-MD/cpptraj/pull/820.

@hectormartinezdev note that cpptraj (and hence pytraj) isn't set up to handle PDB files where the ATOM serial #s are out of order (like in `bad_pocket.txt`). You should sort by ATOM serial # (via e.g. `sort -g -k 2`) before using that with cpptraj/pytraj.

**Comment by drroe** [comment] 2020-06-03 02:09
Behavior should be corrected now.

**Comment by hainm** [comment] 2020-06-03 03:36
I confirm the issue is fixed with cpptraj (and pytraj) in master branch. I can close this issue now. Thanks @drroe.

**Closed by hainm** 2020-06-03 03:36 UTC
