### ISSUE TITLE
dssp kills kernel in Jupyter notebook

### ISSUE THREAD

**Issue by dafwb** [Amber-MD/pytraj#1526] opened 2020-04-02 14:34 UTC
Hello,

I am using pytraj 2.0.2 in a Python3 environment in Jupyter notebook with Python 3.7. pt.load, pt. align and pt.save work fine, but pt.dssp leads to the error: "The kernel appears to have died. It will restart automatically."
Do you have any idea, what the kernel die?

best,
Daniel

Edit: The problem only occurs, when I use trajectories loaded out of pdbs

**Comment by AbdulmalekSaadeddin** [comment] 2020-04-02 22:48
try uninstalling/installing this single library (ipykernel).

**Comment by hainm** [comment] 2020-04-03 02:39
hi @dafwb: may be your pdb file causes segmentation fault when running dssp analysis.
Can you please try your command in terminal to see what happens?

Similar issue: https://github.com/Amber-MD/pytraj/issues/1443

**Comment by dafwb** [comment] 2020-04-03 12:41
Hello,

I tried it in my terminal and got a segmentation gault (I am sorry, that my system is in German):
>>> pdb_traj=pt.load("10100.pdb")
>>> print(pdb_traj)
pytraj.Trajectory, 1 frames: 
Size: 0.000184 (GB)
<Topology: 8237 atoms, 504 residues, 0 mols, PBC with box type = ortho>
           
>>> residues, ss, _ = pt.dssp(pdb_traj, ":201-264", simplified=True)
Speicherzugriffsfehler (Speicherabzug geschrieben)

But i think, the problem is the pt.load() command, because my pdb contains one molecule and somehow the trajectory contains no molecule.
The solution that gives a result that make sense is:
pdbtop=pt.load_topology("10100.pdb")
pdbtop.start_new_mol()
pdb_traj=pt.load("10100.pdb", top=pdbtop)

So my problem is solved, but I think there is an error somewhere in the code.

Best,
Daniel

**Comment by hainm** [comment] 2020-04-03 16:36
Thanks Daniel for your report.

**Comment by hainm** [comment] 2020-06-02 04:25
I've opened a new issue in cpptraj repo too: https://github.com/Amber-MD/cpptraj/issues/819

**Comment by hainm** [comment] 2020-06-03 03:37
The issue is fixed in cpptraj (https://github.com/Amber-MD/cpptraj/pull/820). User don't need to use `start_new_mol` anymore. Thanks @dafwb again.

**Closed by hainm** 2020-06-03 03:37 UTC
