### ISSUE TITLE
Plotting of parameters obtained from Nastruct and Multidihedral

### ISSUE THREAD

**Issue by Manish315** [Amber-MD/pytraj#1519] opened 2020-02-18 16:57 UTC
Hi,

I am new to Pytraj and was going through its various tutorials. Came across 2 commands which are pretty helpful for analysis of nucleic acids trajectories : **nastruct** and **multidihedral**. To get an idea of how the intra and inter- base pair parameters (or dihedral angles) vary for each residue with time, I am saving the data in dataframe format (pandas) and then convert and save it as a csv file:
_dset = pt.multidihedral(traj, dtype='dataframe')
df = pd.DataFrame(dset) 
df.to_csv('multidihedral.csv')_ 

Afterwards, plotting them using matlab.
Is there an easier way out here? For example, lets say I want to know the distribution of **chi** values of all the residues of a 12-mer DNA over 1000 frames. I have seen the way it is done for cpptraj here:http://www.amber.utah.edu/AMBER-workshop/London-2015/DNA-tutorial/ or using seaborn in one of the pytraj tutorials. To do it for all the residues sequentially will be very taxing manually and if it is done only for selected residues you **might** miss some information that has been buried in the non-selected data. I know that it might be highly unlikely, but an overall graphical statistical analysis would be great. Basically, a GUI where you input some parameters and it gives the results in form of relevant plots. I know I might be asking for too much here....;-) 

Similarly, is it possible to observe the variables that I get using nastruct command in the form of relevant histogram plots since it will be much more intuitive than scrolling through numbers? Is there any predefined codes available for the same? Or the way out is to write simple matlab codes for the residues of interest;-(?

Thanks
Manish

**Comment by hainm** [comment] 2020-02-18 17:11
hi @Manish315 `pytraj`'s aim is to give the user the raw output (e.g: in numpy array format) and it's up to user to handle it. I suggest to learn python to get used to `pandas` because `pandas` has many cool features.

**Comment by Manish315** [comment] 2020-02-19 03:00
Ok...thanks for the heads up.

**Comment by Manish315** [comment] 2020-02-20 12:25
Hi Hai,

Sorry for pestering you again. Thanks to your suggestions, I have been able to plot dihedral angles distribution as histogram and KDE plots. Having a little trouble here..couldn't figure out how to plot similar histogram distribution of **base pair** or **base pair ste**p parameters like stretch, stagger, shift, slide etc. on pytraj or cpptraj. Could you please give me some idea on how to do that or guide me towards the relevant text/tutorials?

**Comment by hainm** [comment] 2020-02-21 05:52
uhm, what do you mean? Do you mean you don't know how to get the raw data from pytraj or you don't know how to plot it? What's the difference between dihedral angles distribution and basepair distribution?

**Comment by Manish315** [comment] 2020-02-21 06:40
Hi Hai,

By dihedral angles distributions, I meant the distribution of various dihedral angles present in nucleic acids like alpha, beta, gamma, delta, epsilon, delta and chi for individual nucleotides across the frames. Here is an example of how I plotted it for chi dihedral, after loading the trajectory: 

_# Obtaining only CHI dihedral angle as dataframe type
chi = pt.calc_chin(traj, resrange='1-24', dtype='dataframe')
chi.index=chi.index+1
for i in range(1,25):_
_# Plot a historgram and kernel density estimation:
    sb.distplot(chi['chin_'+str(i)], color="b")
    plt.ylabel('P')
    plt.xlabel('Chi (degree)')_
    _plt.savefig(str(i)+str(Seq[i-1])+'_Chi_DISTRIBUTION')
    plt.clf()_

Similarly, by base pair distribution I meant the distribution of base pair parameters like stretch, stagger for each base pair. I know how to get the raw data from pytraj ..using nastruct command.

_data = pt.nastruct(traj, groove_3dna=True)
data_

Output- <nupars, keys = ['pucker', 'shear', 'stretch', 'stagger', 'buckle', 'prop', 'open', 'hb', 'bp', 'shift', 'slide', 'rise', 'tilt', 'roll', 'twist', 'xdisp', 'ydisp', 'hrise', 'incl', 'tip', 'htwist', 'zp', 'major', 'minor']>

The keys obtained here are the base pair, base pair step  and helical step parameters. Now, my question is how to plot these parameters obtained from nastruct command similar to the case of chi distribution graph?

**Comment by hainm** [comment] 2020-02-21 15:42
hi, you can get the raw data via `data.stagger`. It returns a tuple of basepairs and the raw value.

For example: `data.minor[1][0]` (which is a numpy array) has corresponding data for the basepair `data.minor[0][0]` 
```
>>> data.minor 
(['1G16C', '2G15C', '3G14C', '4C13G', '5G12C', '6C11G', '7C10G', '8C9G'],
 array([[ 13.32927036,  13.403409  ,  13.57159901, ...,  13.26655865,
         13.43054485,  13.4557209 ],
       [ 13.32002068,  13.45918751,  13.63253593, ...,  13.27066231,
         13.42743683,  13.53450871],
       [ 13.34087658,  13.53778553,  13.57062435, ...,  13.29017353,
         13.38542843,  13.46101475]]))
```

You can google how to convert a numpy array to pandas's Dataframe and then you can do the same thing just like the `chi` histogram above. Cheers.

**Comment by Manish315** [comment] 2020-02-22 07:42
Thanks a lot for dumbing it out for me. Should have figured it out myself.
Anyways, thanks for all the help.

Regards 
Manish

**Comment by Manish315** [comment] 2020-02-24 15:01
Hi Hai,

Did what you told and could get the desired graphs for one of my systems. In a separate system, when I try to print data.pucker/data.major/data.minor- it turns out to be fine. But, if i try to print any of the other nupars keys like data.stagger in this case, I get the following error:
![Screenshot from 2020-02-24 20-20-02](https://user-images.githubusercontent.com/61136923/75162348-6c529c00-5743-11ea-9f40-c286fae33028.png)

Further, I tried making some changes in **nucleic_acid_analysis.py**, to see why 960 elements were coming in that array...and couldn't get the head or tail out of it.. Attached below are the changes I made:
![Screenshot from 2020-02-24 20-26-18](https://user-images.githubusercontent.com/61136923/75162939-5db8b480-5744-11ea-9767-7f0d384c4935.png)
Here the output I got was an array of size 960......but why is that the case- it should be 1000, right? Could you please tell where the error might be from my side or is there any other bugs present?

**Comment by hainm** [comment] 2020-02-24 17:27
hi @Manish315, sounds like it's a bug. I will investigate it. Thanks.

**Comment by Manish315** [comment] 2020-02-29 05:48
Hi Hai,

Could you please let me know how long will it take to solve this bug? Cause, I am kinda stuck here... Unable to analyze nucleic acid base parameters.

Thanks for all the help.

Best Regards
Manish

**Comment by hainm** [comment] 2020-02-29 06:14
> Could you please let me know how long will it take to solve this bug?

Do you have a file example to reproduce the bug? It's fine with my testing system.

> Cause, I am kinda stuck here... Unable to analyze nucleic acid base parameters.

You can change the dtype to `cpptraj_dataset` like below

```
In [22]: d = pt.nastruct(t, dtype='cpptraj_dataset')                                                                                         

In [23]: for ds in d: 
    ...:     print(ds.aspect, ds.key, ds.values) 
    ...:     break  # remove this if you want to get all data
    ...:                                                                                                                                     
pucker 2A [191.63916 191.63916]
```

**Comment by Manish315** [comment] 2020-03-02 10:53
Hi Hai,

Sorry for the delay in reply. Was on a vacation and couldn't get back to you quickly. Attached below is an example file containing the system which shows the bug. The tar file contains the .nc as well as .prmtop files. To reproduce the error, just type the following in any python script/notebook:

```
import pytraj as pt
import numpy as np
import pandas as pd
import seaborn as sb
traj=pt.load('run_nowater*.nc', 'wbox_no_water_ions.prmtop')
data = pt.nastruct(traj, groove_3dna=True)
```

`data.stagger`

ValueError                                Traceback (most recent call last)
<ipython-input-3-0e9274ad892f> in <module>
----> 1 data.stagger

_Output-~/anaconda3/lib/python3.7/site-packages/pytraj-2.0.5.dev0-py3.7-linux-x86_64.egg/pytraj/analysis/nucleic_acid_analysis.py in __getattr__(self, aspect)
    190         for idx, arr0 in enumerate(data):
    191             keylist.append(arr0.key)
--> 192             arr[idx] = arr0.values
    193         return keylist, arr.T
    194 

ValueError: could not broadcast input array from shape (960) into shape (1000)_

[new.tar.gz](https://github.com/Amber-MD/pytraj/files/4274861/new.tar.gz)

Thanks
Manish

**Comment by Manish315** [comment] 2020-03-05 18:21
Hi Hai,

Any updates on the reason for the bug?

Thanks
Manish

**Comment by hainm** [comment] 2020-03-05 19:04
I don't have a chance to look at it yet. I am quite busy with my daily work now. I am sorry.
Please see my comment above for alternative code.

**Comment by hainm** [comment] 2020-10-17 14:56
hi @Manish315, the bug is fixed in 
- https://github.com/Amber-MD/cpptraj/pull/854
- https://github.com/Amber-MD/pytraj/pull/1556

If you would like to try, you have to install pytraj (and cpptraj) from source code: https://amber-md.github.io/pytraj/latest/installation.html#from-source-code-hard-way-expert-only

**Closed** 2020-10-19 15:47 UTC
Labels: bug
