### ISSUE TITLE
Files left open with iterload

### ISSUE THREAD

**Issue by hmayes** [Amber-MD/pytraj#1569] opened 2021-02-05 16:10 UTC
Hello!

Following the suggestion on https://amber-md.github.io/pytraj/latest/tips.html#process-many-files, I switched to using iterload. However, I get warnings about resources remaining open (files not closed). I did not see a method to make this happen. Can you provide a suggestion or new means to allow files opened by pytraj to be closed when their analysis is complete?

Thanks!
-heather

**Comment by hainm** [comment] 2021-02-05 16:31
hi @hmayes,

Can you please me show me the code to reproduce the error? I have not seen this before. Thanks.

**Comment by hainm** [comment] 2021-02-05 17:01
And please post the full warning message too.

**Comment by hmayes** [comment] 2021-02-06 01:32
Thank you for your quick response. I figured out why I get the error and you may not--I develop using intelliJ/Pycharm, which uses the malloc debug tool: https://docs.python.org/3/library/tracemalloc.html

As you can see on that page, you can also explicitly use the debug tool.

With that on, running a very simple script/test, e.g. :
`import pytraj as pt

dcd_file_list = ["test.dcd"]
psf_file_name = "test.psf"
traj = pt.iterload(dcd_file_list, psf_file_name)
total_mass = traj.top.mass.sum()
print(f"{total_mass:.2f}")`

I get these warnings:
`/Users/hmayes/opt/miniconda3/envs/polymer-wrangler/lib/python3.8/site-packages/pytraj/all_actions.py:768: ResourceWarning: unclosed file <_io.TextIOWrapper name=6 mode='r' encoding='utf-8'>
  c_dslist, _ = do_action(traj, command, c_action.Action_Radgyr)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/Users/hmayes/opt/miniconda3/envs/polymer-wrangler/lib/python3.8/site-packages/pytraj/all_actions.py:768: ResourceWarning: unclosed file <_io.TextIOWrapper name=8 mode='r' encoding='utf-8'>
  c_dslist, _ = do_action(traj, command, c_action.Action_Radgyr)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
`  

I tried to find the part of pytraj that opens the files:
def iterload(*args, **kwd) calls
def load_traj(filename=None, top=None, *args, **kwd), which calls
def _load(self, filename=None, top=None, frame_slice=(0, -1, 1), stride=None) which calls 
TrajectoryCpptraj._load(self, filename=None, top=None, frame_slice=(0, -1, 1)
which is where I stopped, since that calls cpptraj.

As you may know or suspect, such warnings can often be safely ignored. I was hoping to get this fixed because the trajectory files can be huge, and if I load multiple trajectory files during one instance of python I may have problems. Right now, I'm developing so using only small files, but have run into memory problems before, so I'm on the lookout to resolve memory issues. 

For example, I didn't used to explicitly close plots from pyplot until I ran a script that made so many that it actually caused memory problems. Knowing the size of my trajectory files, you may understand why I would prefer if the files could be closed, e.g. with a command like pt.close(), to parallel pyplot.close()  https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.pyplot.close.html

**Comment by hainm** [comment] 2021-02-06 03:03
hi @hmayes 

> ResourceWarning: unclosed file <_io.TextIOWrapper name=8 mode='r' encoding='utf-8'> c_dslist, _ = do_action(traj, command, c_action.Action_Radgyr)

The file handling is done at C++ (cpptraj) level and python does not know about that. In my opinion, the warning comes from using this code to capture cpptraj's stdout:
https://github.com/Amber-MD/pytraj/blob/8d4f3a759befeca94de6df76d789276e8263b650/pytraj/analysis/c_action/__init__.py#L26

Please try turning off the capturing by patching that code, see here: https://github.com/Amber-MD/pytraj/issues/1498#issuecomment-558360392
(This issue is similar to yours https://github.com/Amber-MD/pytraj/issues/1561#issue-761451391)

**Comment by hainm** [comment] 2021-02-06 03:03
If above solution is correct, then you can safely ignore the warning because it does not relate to open your trajectory files.

**Comment by hmayes** [comment] 2021-02-06 16:29
Instead of capturing all the stdout or stderr, which could discard both that warning and important information and/or desired output, I specifically catch and ignore warnings from the method with the iterload:
`
import pytraj as pt
import warnings

def run_ptraj(dcd_file_list, psf_fname):
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        traj = pt.iterload(dcd_file_list, psf_fname)
        gyr_data = pt.radgyr(traj, mask=':@C1,C2)')
        print(f"{gyr_data[0]:.2f}")
`

I'll keep this in place and contact you if it does become a problem when I start using my package for large files.

**Comment by hainm** [comment] 2021-05-09 04:55
Fixed in #1573

**Closed by hainm** 2021-05-09 04:55 UTC
