### ISSUE TITLE
Speed of autoimage?

### ISSUE THREAD

**Issue by khoroshyy** [Amber-MD/pytraj#1507] opened 2020-01-23 07:04 UTC
Hi.
Hi, I was trying to apply autoimage to a this trajectory..
pytraj.Trajectory, 54500 frames:
Size: 28.277379 (GB)
<Topology: 23213 atoms, 3923 residues, 3035 mols, PBC with box type = ortho>
But it tales ages , I am not even sure if it is working. Is there any way to check progress or speed it up?
Thanks.
Petro.

**Comment by hainm** [comment] 2020-01-23 15:41
Can you try with with just few frames and measure the time?

```
traj2 = traj[:2]
tra2.autoimage()
```

>  speed it up?

Under the hood, it's cpptraj (C++) code so it's already super fast. :D I guess there's something wrong here.

Can you please also try with cpptraj itself? If that's still slow, cpptraj developer can have a look. :D 
https://github.com/Amber-MD/cpptraj

**Comment by hainm** [comment] 2020-01-23 16:51
ah, you can try to see the progress here:

https://github.com/Amber-MD/pytraj#demo-interactive-data-exploration-with-jupyter-notebook-httpjupyterorg

**Comment by khoroshyy** [comment] 2020-01-24 09:23
I have tried with 10 frames some time ago but it did not work also. I have not tried cpptraj yet. May be it has the same problem as nglview had, wrong cell data in trajectory. I will have to check.

**Comment by khoroshyy** [comment] 2020-01-24 10:45
OK, now after I corrected the unit cell data in the trajectory, the command actually finishes running and does what it has to do quite fast. 
I do not understand why the it messes up alpha of the unit cell when loading it. is it problem of my file or of pytraj?
Best.
Petro.

**Comment by hainm** [comment] 2020-01-24 16:17
>  is it problem of my file or of pytraj?

Can you please use 3rd party software (e.g: `ncdump`  to doublecheck your unitcell data in traj).
I dont think pytraj mutates your data if you don't explicitly tell it.

**Comment by khoroshyy** [comment] 2020-01-28 16:34
> Can you please use 3rd party software (e.g: `ncdump` to doublecheck your unitcell data in traj).
> I dont think pytraj mutates your data if you don't explicitly tell it.

If I run ncdump everything  is there. 
For example :
cell_spatial = "abc" ;

 cell_angular =
  "alpha",
  "beta ",
  "gamma" ;

 cell_lengths = 51.17, 61.27, 68.64 ;

 cell_angles = 90, 90, 90 ;
}

**Comment by hainm** [comment] 2020-01-28 16:37
do you have any files (toy model) can be uploaded here so I can reproduce your issue? thanks.

**Comment by khoroshyy** [comment] 2020-01-28 19:41
I will make some...

**Comment by hainm** [comment] 2020-05-26 05:53
hi @khoroshyy: Are you still interested in this issue? If not, I can close this case. Cheers.

**Comment by khoroshyy** [comment] 2020-05-26 08:04
Let me make an example trajectory and I will upload it.

**Comment by hainm** [comment] 2020-09-24 02:21
Since I have not heard from @khoroshyy yet, I go ahead closing this case. Thanks.

**Closed by hainm** 2020-09-24 02:21 UTC
